### ISSUE TITLE
Code about deep learning based method

### ISSUE THREAD

**Issue by Qinrong-NKU** [danini/homography-benchmark#1]
Thank you for your valueable and hard work, could you offer the code about the deep learning based methods? Thank you for your contribution in the field again!!!

**Comment by ducha-aiki** [comment]
@RongQin-cqu Thank you for your interest! We will upload the code gradually, as soon as we clean it up and have time to do so. 
Recently we were super busy with launching Image Matching Challenge 2023 on Kaggle, feel free to check it out :)
https://www.kaggle.com/competitions/image-matching-challenge-2023/overview

**Comment by Qinrong-NKU** [comment]
Thank you very much for not only your work but also your kind. Your valueable code will help our work a lot, and we will also cite your paper in our paper for your contribution in this field.&nbsp;&nbsp;




学渣
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "danini/homography-benchmark"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月12日(星期三) 晚上7:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [danini/homography-benchmark] Code about deep learning based method (Issue #1)





 
@RongQin-cqu Thank you for your interest! We will upload the code gradually, as soon as we clean it up and have time to do so.
 Recently we were super busy with launching Image Matching Challenge 2023 on Kaggle, feel free to check it out :)
 https://www.kaggle.com/competitions/image-matching-challenge-2023/overview

**Comment by Qinrong-NKU** [comment]
Hello, can you just offer the code of any deep learning based model (OANet/CLNet) first even without clean so that we can test our method on your great dataset? Thank you for your hard work.

**Comment by ducha-aiki** [comment]
Here you go

https://github.com/danini/homography-benchmark#deep-prefiltering

Sorry for the huge delay.
